/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_string_test.check" instead.
 */

#include <check.h>

#line 1 "s21_string_test.check"
#include <stdio.h>
#include <stdlib.h>
#include "s21_string/s21_string.h"

START_TEST(s21_strcat_normal)
{
#line 6
char str_1[20] = "hello";
char str_2[20] = "hello";
char *src = "world";
char *s21_result = s21_strcat(str_1, src);
char *lib_result = strcat(str_2, src);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strcat_first_str_empty)
{
#line 14
char str_1[20];
str_1[0] = '\0';
char str_2[20];
str_2[0] = '\0';
char *src = "world";
char *s21_result = s21_strcat(str_1, src);
char *lib_result = strcat(str_2, src);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strcat_second_str_empty)
{
#line 24
char str_1[20] = "hello";
char str_2[20] = "hello";
char *src = "";
char* s21_result = s21_strcat(str_1, src);
char* lib_result = strcat(str_2, src);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strcat_both_str_empty)
{
#line 32
char str_1[20] = "";
char str_2[20] = "";
char *src = "";
char* s21_result = s21_strcat(str_1, src);
char* lib_result = strcat(str_2, src);
ck_assert_str_eq(s21_result, lib_result);


}
END_TEST

START_TEST(s21_strncat_normal)
{
#line 41
char str_1[20] = "hello";
char str_2[20] = "hello";
char *src = "world";
s21_size_t n = 3;
char *s21_result = s21_strncat(str_1, src, n);
char *lib_result = strncat(str_2, src, n);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strncat_first_str_empty)
{
#line 50
char str_1[20];
str_1[0] = '\0';
char str_2[20];
str_2[0] = '\0';
char *src = "world";
s21_size_t n = 3;
char *s21_result = s21_strncat(str_1, src, n);
char *lib_result = strncat(str_2, src, n);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strncat_second_str_empty)
{
#line 61
char str_1[20] = "hello";
char str_2[20] = "hello";
char *src = "";
s21_size_t n = 3;
char* s21_result = s21_strncat(str_1, src, n);
char* lib_result = strncat(str_2, src, n);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strncat_both_str_empty)
{
#line 70
char str_1[20] = "";
char str_2[20] = "";
char *src = "";
s21_size_t n = 3;
char* s21_result = s21_strncat(str_1, src, n);
char* lib_result = strncat(str_2, src, n);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strncat_size_empty)
{
#line 79
char str_1[20] = "hello";
char str_2[20] = "hello";
char *src = "world";
s21_size_t n = 0;
char* s21_result = s21_strncat(str_1, src, n);
char* lib_result = strncat(str_2, src, n);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strncat_all_empty)
{
#line 88
char str_1[20] = "";
char str_2[20] = "";
char *src = "";
s21_size_t n = 0;
char* s21_result = s21_strncat(str_1, src, n);
char* lib_result = strncat(str_2, src, n);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strtok_normal)
{
#line 97
char s21_test_str[30] = "one/two.three?four";
char lib_test_str[30] = "one/two.three?four";
char* step = "./?";
char* s21_result = s21_strtok(s21_test_str, step);
char* lib_result = strtok(lib_test_str, step);
while (s21_result != s21_NULL && lib_result != s21_NULL) {
    ck_assert_str_eq(s21_result, lib_result);
    s21_result = s21_strtok(s21_NULL, step);
    lib_result = strtok(s21_NULL, step);
}
ck_assert_ptr_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strtok_no_delimetr)
{
#line 110
char s21_test_str[30] = "one/two.three?four";
char lib_test_str[30] = "one/two.three?four";
char* step = "$()-";
char* s21_result = s21_strtok(s21_test_str, step);
char* lib_result = strtok(lib_test_str, step);
while (s21_result != s21_NULL && lib_result != s21_NULL) {
    ck_assert_str_eq(s21_result, lib_result);
    s21_result = s21_strtok(s21_NULL, step);
    lib_result = strtok(s21_NULL, step);
}
ck_assert_ptr_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strtok_empty)
{
#line 123
char s21_test_str[30] = "";
char lib_test_str[30] = "";
char* step = "$()-";
char* s21_result = s21_strtok(s21_test_str, step);
char* lib_result = strtok(lib_test_str, step);
ck_assert_ptr_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strerror_positive_0)
{
#line 131
char* s21_test_str = s21_strerror(0);
char* lib_test_str = strerror(0);
ck_assert_str_eq(s21_test_str, lib_test_str);

}
END_TEST

START_TEST(s21_strerror_positive_106)
{
#line 136
char* s21_test_str = s21_strerror(106);
char* lib_test_str = strerror(106);
ck_assert_str_eq(s21_test_str, lib_test_str);

}
END_TEST

START_TEST(s21_strerror_negative_minus1)
{
#line 141
char* s21_test_str = s21_strerror(-1);
char* lib_test_str = strerror(-1);
ck_assert_str_eq(s21_test_str, lib_test_str);

}
END_TEST

START_TEST(s21_strerror_negative_107)
{
#line 146
char* s21_test_str = s21_strerror(107);
char* lib_test_str = strerror(107);
ck_assert_str_eq(s21_test_str, lib_test_str);

}
END_TEST

START_TEST(s21_strerror_negative_minus1000)
{
#line 151
char* s21_test_str = s21_strerror(-1000);
char* lib_test_str = strerror(-1000);
ck_assert_str_eq(s21_test_str, lib_test_str);

}
END_TEST

START_TEST(s21_strerror_negative_1000)
{
#line 156
char* s21_test_str = s21_strerror(1000);
char* lib_test_str = strerror(1000);
ck_assert_str_eq(s21_test_str, lib_test_str);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_strcat_normal);
    tcase_add_test(tc1_1, s21_strcat_first_str_empty);
    tcase_add_test(tc1_1, s21_strcat_second_str_empty);
    tcase_add_test(tc1_1, s21_strcat_both_str_empty);
    tcase_add_test(tc1_1, s21_strncat_normal);
    tcase_add_test(tc1_1, s21_strncat_first_str_empty);
    tcase_add_test(tc1_1, s21_strncat_second_str_empty);
    tcase_add_test(tc1_1, s21_strncat_both_str_empty);
    tcase_add_test(tc1_1, s21_strncat_size_empty);
    tcase_add_test(tc1_1, s21_strncat_all_empty);
    tcase_add_test(tc1_1, s21_strtok_normal);
    tcase_add_test(tc1_1, s21_strtok_no_delimetr);
    tcase_add_test(tc1_1, s21_strtok_empty);
    tcase_add_test(tc1_1, s21_strerror_positive_0);
    tcase_add_test(tc1_1, s21_strerror_positive_106);
    tcase_add_test(tc1_1, s21_strerror_negative_minus1);
    tcase_add_test(tc1_1, s21_strerror_negative_107);
    tcase_add_test(tc1_1, s21_strerror_negative_minus1000);
    tcase_add_test(tc1_1, s21_strerror_negative_1000);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
