/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_test.check" instead.
 */

#include <check.h>

#line 1 "s21_test.check"
#include <stdio.h>
#include <stdlib.h>
#include "s21_string.h"




START_TEST(memcmp_1)
{
#line 9
char s1[] = "hello world";
char s2[] = "hello world";
ck_assert_int_eq(memcmp(s1,s2, 9),s21_memcmp(s1,s2, 9));

}
END_TEST

START_TEST(memcmp_2)
{
#line 14
char str1[] = "HELLO555";
char str2[] = "HELLO";
ck_assert_int_eq(memcmp(str1,str2, 9), s21_memcmp(str1,str2, 9));

}
END_TEST

START_TEST(memcmp_3)
{
#line 19
char str1[] = "HELLO";
char str2[] = "";
ck_assert_int_eq(memcmp(str1,str2, 9), s21_memcmp(str1,str2, 9));

}
END_TEST

START_TEST(memcmp_4)
{
#line 24
char str1[] = "";
char str2[] = "";
ck_assert_int_eq(memcmp(str1,str2, 9), s21_memcmp(str1,str2, 9));

}
END_TEST

START_TEST(memcmp_5)
{
#line 29
char str1[] = "*^$%^&)*";
char str2[] = "^%$^R(&*";
ck_assert_int_eq(memcmp(str1,str2, 0), s21_memcmp(str1,str2, 0));

}
END_TEST

START_TEST(memcmp_6)
{
#line 34
char str1[] = "%^&*";
char str2[] = "^&*(";
ck_assert_int_eq(memcmp(str1,str2, -3), s21_memcmp(str1,str2, -3));







}
END_TEST

START_TEST(memcpy_1)
{
#line 45
char str1[10] = "1234";
char str2[10] = "";
ck_assert_ptr_eq(memcpy(str2, str1, 2), s21_memcpy(str2, str1, 2));

}
END_TEST

START_TEST(memcpy_2)
{
#line 50
char str1[10] = "a";
char str2[10] = "1234456";
ck_assert_ptr_eq(memcpy(str2, str1, 10), s21_memcpy(str2, str1, 10));

}
END_TEST

START_TEST(memcpy_3)
{
#line 55
char str1[] = "";
char str2[10] = "1234456\0\n\t";
ck_assert_ptr_eq(memcpy(str2, str1, 1), s21_memcpy(str2, str1, 1));

}
END_TEST

START_TEST(memcpy_4)
{
#line 60
char str1[10] = "";
char str2[10] = "1234456";
ck_assert_ptr_eq(memcpy(str2, str1, 3), s21_memcpy(str2, str1, 3));

}
END_TEST

START_TEST(memcpy_5)
{
#line 65
char str1[] = "";
char str2[] = "";
ck_assert_ptr_eq(memcpy(str2, str1, 1), s21_memcpy(str2, str1, 1));

}
END_TEST

START_TEST(memcpy_6)
{
#line 70
char str1[] = "";
char str2[] = "";
ck_assert_ptr_eq(memcpy(str2, str1, 0), s21_memcpy(str2, str1, 0));






}
END_TEST

START_TEST(memmove_1)
{
#line 80
char str1[10] = "12345";
char str2[10] = "123";
ck_assert_ptr_eq(memmove(&str2[2], &str1[3], 3), s21_memmove(&str2[2], &str1[3], 3));

}
END_TEST

START_TEST(memmove_2)
{
#line 85
char str1[10] = "123767";
ck_assert_ptr_eq(memmove(&str1[2], &str1[3], 3), s21_memmove(&str1[2], &str1[3], 3));

}
END_TEST

START_TEST(memmove_3)
{
#line 89
char str1[10] = "";
char str2[10] = "";
ck_assert_ptr_eq(memmove(str1, str2, 3), s21_memmove(str1, str2, 3));

}
END_TEST

START_TEST(memmove_4)
{
#line 94
char str1[10] = "\0\t\n\a";
char str2[10] = "";
ck_assert_ptr_eq(memmove(str2, str1, 3), s21_memmove(str2, str1, 3));

}
END_TEST

START_TEST(memmove_5)
{
#line 99
char str1[] = "\0\t\n\a";
char str2[] = "";
ck_assert_ptr_eq(memmove(str2, str1, 0), s21_memmove(str2, str1, 0));




}
END_TEST

START_TEST(memset_1)
{
#line 107
char str1[] = "qqqqqq";
ck_assert_ptr_eq(memset(str1, '1', 4), s21_memset(str1, '1', 4));

}
END_TEST

START_TEST(memset_2)
{
#line 111
char str1[10] = "";
ck_assert_ptr_eq(memset(str1, '1', 3), s21_memset(str1, '1', 3));

}
END_TEST

START_TEST(memset_3)
{
#line 115
char str1[10] = "qqqqqqq";
ck_assert_ptr_eq(memset(str1, '\0', 10), s21_memset(str1, '\0', 10));

}
END_TEST

START_TEST(memset_4)
{
#line 119
char str1[10] = "\0\0\0\0\0";
ck_assert_ptr_eq(memset(str1, '\n', 10), s21_memset(str1, '\n', 10));

}
END_TEST

START_TEST(memset_5)
{
#line 123
char str1[10] = "\0\0\0\0\0";
ck_assert_ptr_eq(memset(str1, '\n', 0), s21_memset(str1, '\n', 0));



}
END_TEST

START_TEST(strcpy_1)
{
#line 129
char str1[10] = "123456789";
char str2[10] = "";
ck_assert_ptr_eq(strcpy(str2, str1), s21_strcpy(str2, str1));

}
END_TEST

START_TEST(strcpy_2)
{
#line 134
char str1[10] = "123456789";
char str2[10] = "1231231231";
ck_assert_ptr_eq(strcpy(str2, str1), s21_strcpy(str2, str1));

}
END_TEST

START_TEST(strcpy_3)
{
#line 139
char str1[10] = "";
char str2[10] = "";
ck_assert_ptr_eq(strcpy(str2, str1), s21_strcpy(str2, str1));

}
END_TEST

START_TEST(strcpy_4)
{
#line 144
char str1[] = "\0\t\n\a";
char str2[] = "";
ck_assert_ptr_eq(strcpy(str2, str1), s21_strcpy(str2, str1));

}
END_TEST

START_TEST(strcpy_5)
{
#line 149
char str1[] = "";
char str2[] = "                    ";
ck_assert_ptr_eq(strcpy(str2, str1), s21_strcpy(str2, str1));





}
END_TEST

START_TEST(strncpy_1)
{
#line 158
char str1[10] = "123456789";
char str2[10] = "";
ck_assert_ptr_eq(strncpy(str2, str1, 10), s21_strncpy(str2, str1, 10));

}
END_TEST

START_TEST(strncpy_2)
{
#line 163
char str1[10] = "1234";
char str2[10] = "";
ck_assert_ptr_eq(strncpy(str2, str1, 0), s21_strncpy(str2, str1, 0));

}
END_TEST

START_TEST(strncpy_3)
{
#line 168
char str1[10] = "\0\t\n";
char str2[10] = "";
ck_assert_ptr_eq(strncpy(str2, str1, 3), s21_strncpy(str2, str1, 3));

}
END_TEST

START_TEST(strncpy_4)
{
#line 173
char str1[10] = "";
char str2[10] = "";
ck_assert_ptr_eq(strncpy(str2, str1, 3), s21_strncpy(str2, str1, 3));

}
END_TEST

START_TEST(strncpy_5)
{
#line 178
char str1[10] = "2132313";
char str2[10] = "1111";
ck_assert_ptr_eq(strncpy(str2, str1, 3), s21_strncpy(str2, str1, 3));



}
END_TEST

START_TEST(memchr_1)
{
#line 185
char str1[10] = "2132313";
int a = 49;
ck_assert_ptr_eq(memchr(str1, a, 5), s21_memchr(str1, a, 5));

}
END_TEST

START_TEST(memchr_2)
{
#line 190
char str1[10] = "";
int a = '\0';
ck_assert_ptr_eq(memchr(str1, a, 10), s21_memchr(str1, a, 10));

}
END_TEST

START_TEST(memchr_3)
{
#line 195
char str1[10] = "112323";
int a = 127;
ck_assert_ptr_eq(memchr(str1, a, 4), s21_memchr(str1, a, 4));

}
END_TEST

START_TEST(memchr_4)
{
#line 200
char str1[10] = "";
int a = 84924932;
ck_assert_ptr_eq(memchr(str1, a, 14), s21_memchr(str1, a, 14));

}
END_TEST

START_TEST(memchr_5)
{
#line 205
char str1[] = "";
int a = 1000000000;
ck_assert_ptr_eq(memchr(str1, a, 1), s21_memchr(str1, a, 1));




}
END_TEST

START_TEST(strcmp_1)
{
#line 213
ck_assert_int_eq(strcmp("qwerty", "qwerty"), s21_strcmp("qwerty", "qwerty"));

}
END_TEST

START_TEST(strcmp_2)
{
#line 216
char *str1 = "equal";
char *str2 = "equaly";
ck_assert_int_eq(strcmp(str1, str2), s21_strcmp(str1, str2));

}
END_TEST

START_TEST(strcmp_3)
{
#line 221
char *str1 = "equal";
char *str3 = "qwert";
ck_assert_int_eq(strcmp(str1, str3), s21_strcmp(str1, str3));

}
END_TEST

START_TEST(strcmp_4)
{
#line 226
char *str1 = "equal";
ck_assert_int_eq(strcmp(str1, "equal"), s21_strcmp(str1, "equal"));

}
END_TEST

START_TEST(strcmp_5)
{
#line 230
char *str1 = "123@##%@";
char *str2 = "123@@$??";
ck_assert_int_eq(strcmp(str1, str2), s21_strcmp(str1, str2));

}
END_TEST

START_TEST(strcnmp_1)
{
#line 235
ck_assert_int_eq(strncmp("qwerty", "qwerty", 6), s21_strncmp("qwerty", "qwerty", 6));

}
END_TEST

START_TEST(strncmp_2)
{
#line 238
char *str1 = "equal";
char *str2 = "equaly";
ck_assert_int_eq(strncmp(str1, str2, 5), s21_strncmp(str1, str2, 5));

}
END_TEST

START_TEST(strncmp_3)
{
#line 243
char *str1 = "equal";
char *str3 = "qwert";
ck_assert_int_eq(strncmp(str1, str3, 1), s21_strncmp(str1, str3, 1));

}
END_TEST

START_TEST(strncmp_4)
{
#line 248
char *str1 = "equal";
ck_assert_int_eq(strncmp(str1, "equal", 2), s21_strncmp(str1, "equal", 2));

}
END_TEST

START_TEST(strncmp_5)
{
#line 252
char *str1 = "123@##%@";
char *str2 = "123@@$??";
ck_assert_int_eq(strncmp(str1, str2, 10), s21_strncmp(str1, str2, 10));

}
END_TEST

START_TEST(strlen_1)
{
#line 257
ck_assert_int_eq(strlen("qwerty"), s21_strlen("qwerty"));

}
END_TEST

START_TEST(strlen_2)
{
#line 260
char *str1 = "equal";
ck_assert_int_eq(strlen(str1), s21_strlen(str1));

}
END_TEST

START_TEST(strlen_3)
{
#line 264
char *str1 = "e";
ck_assert_int_eq(strlen(str1), s21_strlen(str1));

}
END_TEST

START_TEST(strlen_4)
{
#line 268
char *str1 = " ";
ck_assert_int_eq(strlen(str1), s21_strlen(str1));

}
END_TEST

START_TEST(strlen_5)
{
#line 272
char *str1 = "";
ck_assert_int_eq(strlen(str1), s21_strlen(str1));

}
END_TEST

START_TEST(strspn_1)
{
#line 276
ck_assert_int_eq(strspn("qwerty", "qwerty"), s21_strspn("qwerty", "qwerty"));

}
END_TEST

START_TEST(strspn_2)
{
#line 279
char *str1 = "equal";
char *str2 = "e";
ck_assert_int_eq(strspn(str1, str2), s21_strspn(str1, str2));

}
END_TEST

START_TEST(strspn_3)
{
#line 284
char *str1 = "equal";
char *str3 = "wrt";
ck_assert_int_eq(strspn(str1, str3), s21_strspn(str1, str3));

}
END_TEST

START_TEST(strspn_4)
{
#line 289
char *str1 = "equal";
char *str2 = "";
ck_assert_int_eq(strspn(str1, str2), s21_strspn(str1, str2));

}
END_TEST

START_TEST(strspn_5)
{
#line 294
char *str1 = "123";
char *str2 = "123@@$??";
ck_assert_int_eq(strspn(str1, str2), s21_strspn(str1, str2));

}
END_TEST

START_TEST(strcspn_1)
{
#line 299
ck_assert_int_eq(strcspn("qwerty", "qwerty"), s21_strcspn("qwerty", "qwerty"));

}
END_TEST

START_TEST(strcspn_2)
{
#line 302
char *str1 = "equal";
char *str2 = "e";
ck_assert_int_eq(strcspn(str1, str2), s21_strcspn(str1, str2));

}
END_TEST

START_TEST(strcspn_3)
{
#line 307
char *str1 = "equal";
char *str3 = "wrt";
ck_assert_int_eq(strcspn(str1, str3), s21_strcspn(str1, str3));

}
END_TEST

START_TEST(strcspn_4)
{
#line 312
char *str1 = "equal";
char *str2 = "";
ck_assert_int_eq(strcspn(str1, str2), s21_strcspn(str1, str2));

}
END_TEST

START_TEST(strcspn_5)
{
#line 317
char *str1 = "123";
char *str2 = "123@@$??";
ck_assert_int_eq(strcspn(str1, str2), s21_strcspn(str1, str2));

}
END_TEST

START_TEST(strstr_1)
{
#line 322
ck_assert_pstr_eq(strstr("qwerty", "qwe"), s21_strstr("qwerty", "qwe"));

}
END_TEST

START_TEST(strstr_2)
{
#line 325
char *str1 = "equal";
char *str2 = "qual";
ck_assert_pstr_eq(strstr(str1, str2), s21_strstr(str1, str2));

}
END_TEST

START_TEST(strstr_3)
{
#line 330
char *str1 = "equal";
char *str3 = "quf";
ck_assert_pstr_eq(strstr(str1, str3), s21_strstr(str1, str3));

}
END_TEST

START_TEST(strstr_4)
{
#line 335
char *str1 = "equal";
char *str2 = "";
ck_assert_pstr_eq(strstr(str1, str2), s21_strstr(str1, str2));

}
END_TEST

START_TEST(strstr_5)
{
#line 340
char *str1 = "123";
char *str2 = "123qwerty123q";
ck_assert_pstr_eq(strstr(str1, str2), s21_strstr(str1, str2));

}
END_TEST

START_TEST(strrchr_1)
{
#line 345
ck_assert_pstr_eq(strrchr("qwerty", 'q'), s21_strrchr("qwerty", 'q'));

}
END_TEST

START_TEST(strrchr_2)
{
#line 348
char *str1 = "equal";
char str2 = 'q';
ck_assert_pstr_eq(strrchr(str1, str2), s21_strrchr(str1, str2));

}
END_TEST

START_TEST(strrchr_3)
{
#line 353
char *str1 = "equal";
char str2 = 'y';
ck_assert_pstr_eq(strrchr(str1, str2), s21_strrchr(str1, str2));

}
END_TEST

START_TEST(strrchr_4)
{
#line 358
char *str1 = "equal";
char str2 = ' ';
ck_assert_pstr_eq(strrchr(str1, str2), s21_strrchr(str1, str2));

}
END_TEST

START_TEST(strrchr_5)
{
#line 363
char *str1 = "qwe";
char str2 = '\0';
ck_assert_pstr_eq(strrchr(str1, str2), s21_strrchr(str1, str2));

}
END_TEST

START_TEST(strpbrk_1)
{
#line 368
ck_assert_pstr_eq(strpbrk("qwerty", "equ"), s21_strpbrk("qwerty", "equ"));

}
END_TEST

START_TEST(strpbrk_2)
{
#line 371
char *str1 = "equal";
char *str2 = "qq";
ck_assert_pstr_eq(strpbrk(str1, str2), s21_strpbrk(str1, str2));

}
END_TEST

START_TEST(strpbrk_3)
{
#line 376
char *str1 = "equal";
char *str2 = "yhht";
ck_assert_pstr_eq(strpbrk(str1, str2), s21_strpbrk(str1, str2));

}
END_TEST

START_TEST(strpbrk_4)
{
#line 381
char *str1 = "equal";
char *str2 = "m";
ck_assert_pstr_eq(strpbrk(str1, str2), s21_strpbrk(str1, str2));

}
END_TEST

START_TEST(strpbrk_5)
{
#line 386
char *str1 = "qwe";
char *str2 = "\0";
ck_assert_pstr_eq(strpbrk(str1, str2), s21_strpbrk(str1, str2));

}
END_TEST

START_TEST(strchr_1)
{
#line 391
ck_assert_ptr_eq(strchr("qwerty", 'q'), s21_strchr("qwerty", 'q'));

}
END_TEST

START_TEST(strchr_2)
{
#line 394
char *str1 = "equal";
char str2 = 'e';
ck_assert_ptr_eq(strchr(str1, str2), s21_strchr(str1, str2));

}
END_TEST

START_TEST(strchr_3)
{
#line 399
char *str1 = "equal";
char str2 = 'f';
ck_assert_ptr_eq(strchr(str1, str2), s21_strchr(str1, str2));

}
END_TEST

START_TEST(strchr_4)
{
#line 404
char *str1 = "equal";
char str2 = ' ';
ck_assert_ptr_eq(strchr(str1, str2), s21_strchr(str1, str2));

}
END_TEST

START_TEST(strchr_5)
{
#line 409
char *str1 = "qwe";
char str2 = '\0';
ck_assert_ptr_eq(strchr(str1, str2), s21_strchr(str1, str2));



}
END_TEST

START_TEST(s21_strcat_normal)
{
#line 416
char str_1[20] = "hello";
char str_2[20] = "hello";
char *src = "world";
char *s21_result = s21_strcat(str_1, src);
char *lib_result = strcat(str_2, src);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strcat_first_str_empty)
{
#line 424
char str_1[20];
str_1[0] = '\0';
char str_2[20];
str_2[0] = '\0';
char *src = "world";
char *s21_result = s21_strcat(str_1, src);
char *lib_result = strcat(str_2, src);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strcat_second_str_empty)
{
#line 434
char str_1[20] = "hello";
char str_2[20] = "hello";
char *src = "";
char* s21_result = s21_strcat(str_1, src);
char* lib_result = strcat(str_2, src);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strcat_both_str_empty)
{
#line 442
char str_1[20] = "";
char str_2[20] = "";
char *src = "";
char* s21_result = s21_strcat(str_1, src);
char* lib_result = strcat(str_2, src);
ck_assert_str_eq(s21_result, lib_result);


}
END_TEST

START_TEST(s21_strncat_normal)
{
#line 451
char str_1[20] = "hello";
char str_2[20] = "hello";
char *src = "world";
s21_size_t n = 3;
char *s21_result = s21_strncat(str_1, src, n);
char *lib_result = strncat(str_2, src, n);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strncat_first_str_empty)
{
#line 460
char str_1[20];
str_1[0] = '\0';
char str_2[20];
str_2[0] = '\0';
char *src = "world";
s21_size_t n = 3;
char *s21_result = s21_strncat(str_1, src, n);
char *lib_result = strncat(str_2, src, n);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strncat_second_str_empty)
{
#line 471
char str_1[20] = "hello";
char str_2[20] = "hello";
char *src = "";
s21_size_t n = 3;
char* s21_result = s21_strncat(str_1, src, n);
char* lib_result = strncat(str_2, src, n);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strncat_both_str_empty)
{
#line 480
char str_1[20] = "";
char str_2[20] = "";
char *src = "";
s21_size_t n = 3;
char* s21_result = s21_strncat(str_1, src, n);
char* lib_result = strncat(str_2, src, n);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strncat_size_empty)
{
#line 489
char str_1[20] = "hello";
char str_2[20] = "hello";
char *src = "world";
s21_size_t n = 0;
char* s21_result = s21_strncat(str_1, src, n);
char* lib_result = strncat(str_2, src, n);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strncat_all_empty)
{
#line 498
char str_1[20] = "";
char str_2[20] = "";
char *src = "";
s21_size_t n = 0;
char* s21_result = s21_strncat(str_1, src, n);
char* lib_result = strncat(str_2, src, n);
ck_assert_str_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strtok_normal)
{
#line 507
char s21_test_str[30] = "one/two.three?four";
char lib_test_str[30] = "one/two.three?four";
char* step = "./?";
char* s21_result = s21_strtok(s21_test_str, step);
char* lib_result = strtok(lib_test_str, step);
while (s21_result != s21_NULL && lib_result != s21_NULL) {
    ck_assert_str_eq(s21_result, lib_result);
    s21_result = s21_strtok(s21_NULL, step);
    lib_result = strtok(s21_NULL, step);
}
ck_assert_ptr_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strtok_no_delimetr)
{
#line 520
char s21_test_str[30] = "one/two.three?four";
char lib_test_str[30] = "one/two.three?four";
char* step = "$()-";
char* s21_result = s21_strtok(s21_test_str, step);
char* lib_result = strtok(lib_test_str, step);
while (s21_result != s21_NULL && lib_result != s21_NULL) {
    ck_assert_str_eq(s21_result, lib_result);
    s21_result = s21_strtok(s21_NULL, step);
    lib_result = strtok(s21_NULL, step);
}
ck_assert_ptr_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strtok_empty)
{
#line 533
char s21_test_str[30] = "";
char lib_test_str[30] = "";
char* step = "$()-";
char* s21_result = s21_strtok(s21_test_str, step);
char* lib_result = strtok(lib_test_str, step);
ck_assert_ptr_eq(s21_result, lib_result);

}
END_TEST

START_TEST(s21_strerror_positive_0)
{
#line 541
char* s21_test_str = s21_strerror(0);
char* lib_test_str = strerror(0);
ck_assert_str_eq(s21_test_str, lib_test_str);

}
END_TEST

START_TEST(s21_strerror_positive_106)
{
#line 546
char* s21_test_str = s21_strerror(106);
char* lib_test_str = strerror(106);
ck_assert_str_eq(s21_test_str, lib_test_str);

}
END_TEST

START_TEST(s21_strerror_negative_minus1)
{
#line 551
char* s21_test_str = s21_strerror(-1);
char* lib_test_str = strerror(-1);
ck_assert_str_eq(s21_test_str, lib_test_str);

}
END_TEST

START_TEST(s21_strerror_negative_107)
{
#line 556
char* s21_test_str = s21_strerror(107);
char* lib_test_str = strerror(107);
ck_assert_str_eq(s21_test_str, lib_test_str);

}
END_TEST

START_TEST(s21_strerror_negative_minus1000)
{
#line 561
char* s21_test_str = s21_strerror(-1000);
char* lib_test_str = strerror(-1000);
ck_assert_str_eq(s21_test_str, lib_test_str);

}
END_TEST

START_TEST(s21_strerror_negative_1000)
{
#line 566
char* s21_test_str = s21_strerror(1000);
char* lib_test_str = strerror(1000);
ck_assert_str_eq(s21_test_str, lib_test_str);

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, memcmp_1);
    tcase_add_test(tc1_1, memcmp_2);
    tcase_add_test(tc1_1, memcmp_3);
    tcase_add_test(tc1_1, memcmp_4);
    tcase_add_test(tc1_1, memcmp_5);
    tcase_add_test(tc1_1, memcmp_6);
    tcase_add_test(tc1_1, memcpy_1);
    tcase_add_test(tc1_1, memcpy_2);
    tcase_add_test(tc1_1, memcpy_3);
    tcase_add_test(tc1_1, memcpy_4);
    tcase_add_test(tc1_1, memcpy_5);
    tcase_add_test(tc1_1, memcpy_6);
    tcase_add_test(tc1_1, memmove_1);
    tcase_add_test(tc1_1, memmove_2);
    tcase_add_test(tc1_1, memmove_3);
    tcase_add_test(tc1_1, memmove_4);
    tcase_add_test(tc1_1, memmove_5);
    tcase_add_test(tc1_1, memset_1);
    tcase_add_test(tc1_1, memset_2);
    tcase_add_test(tc1_1, memset_3);
    tcase_add_test(tc1_1, memset_4);
    tcase_add_test(tc1_1, memset_5);
    tcase_add_test(tc1_1, strcpy_1);
    tcase_add_test(tc1_1, strcpy_2);
    tcase_add_test(tc1_1, strcpy_3);
    tcase_add_test(tc1_1, strcpy_4);
    tcase_add_test(tc1_1, strcpy_5);
    tcase_add_test(tc1_1, strncpy_1);
    tcase_add_test(tc1_1, strncpy_2);
    tcase_add_test(tc1_1, strncpy_3);
    tcase_add_test(tc1_1, strncpy_4);
    tcase_add_test(tc1_1, strncpy_5);
    tcase_add_test(tc1_1, memchr_1);
    tcase_add_test(tc1_1, memchr_2);
    tcase_add_test(tc1_1, memchr_3);
    tcase_add_test(tc1_1, memchr_4);
    tcase_add_test(tc1_1, memchr_5);
    tcase_add_test(tc1_1, strcmp_1);
    tcase_add_test(tc1_1, strcmp_2);
    tcase_add_test(tc1_1, strcmp_3);
    tcase_add_test(tc1_1, strcmp_4);
    tcase_add_test(tc1_1, strcmp_5);
    tcase_add_test(tc1_1, strcnmp_1);
    tcase_add_test(tc1_1, strncmp_2);
    tcase_add_test(tc1_1, strncmp_3);
    tcase_add_test(tc1_1, strncmp_4);
    tcase_add_test(tc1_1, strncmp_5);
    tcase_add_test(tc1_1, strlen_1);
    tcase_add_test(tc1_1, strlen_2);
    tcase_add_test(tc1_1, strlen_3);
    tcase_add_test(tc1_1, strlen_4);
    tcase_add_test(tc1_1, strlen_5);
    tcase_add_test(tc1_1, strspn_1);
    tcase_add_test(tc1_1, strspn_2);
    tcase_add_test(tc1_1, strspn_3);
    tcase_add_test(tc1_1, strspn_4);
    tcase_add_test(tc1_1, strspn_5);
    tcase_add_test(tc1_1, strcspn_1);
    tcase_add_test(tc1_1, strcspn_2);
    tcase_add_test(tc1_1, strcspn_3);
    tcase_add_test(tc1_1, strcspn_4);
    tcase_add_test(tc1_1, strcspn_5);
    tcase_add_test(tc1_1, strstr_1);
    tcase_add_test(tc1_1, strstr_2);
    tcase_add_test(tc1_1, strstr_3);
    tcase_add_test(tc1_1, strstr_4);
    tcase_add_test(tc1_1, strstr_5);
    tcase_add_test(tc1_1, strrchr_1);
    tcase_add_test(tc1_1, strrchr_2);
    tcase_add_test(tc1_1, strrchr_3);
    tcase_add_test(tc1_1, strrchr_4);
    tcase_add_test(tc1_1, strrchr_5);
    tcase_add_test(tc1_1, strpbrk_1);
    tcase_add_test(tc1_1, strpbrk_2);
    tcase_add_test(tc1_1, strpbrk_3);
    tcase_add_test(tc1_1, strpbrk_4);
    tcase_add_test(tc1_1, strpbrk_5);
    tcase_add_test(tc1_1, strchr_1);
    tcase_add_test(tc1_1, strchr_2);
    tcase_add_test(tc1_1, strchr_3);
    tcase_add_test(tc1_1, strchr_4);
    tcase_add_test(tc1_1, strchr_5);
    tcase_add_test(tc1_1, s21_strcat_normal);
    tcase_add_test(tc1_1, s21_strcat_first_str_empty);
    tcase_add_test(tc1_1, s21_strcat_second_str_empty);
    tcase_add_test(tc1_1, s21_strcat_both_str_empty);
    tcase_add_test(tc1_1, s21_strncat_normal);
    tcase_add_test(tc1_1, s21_strncat_first_str_empty);
    tcase_add_test(tc1_1, s21_strncat_second_str_empty);
    tcase_add_test(tc1_1, s21_strncat_both_str_empty);
    tcase_add_test(tc1_1, s21_strncat_size_empty);
    tcase_add_test(tc1_1, s21_strncat_all_empty);
    tcase_add_test(tc1_1, s21_strtok_normal);
    tcase_add_test(tc1_1, s21_strtok_no_delimetr);
    tcase_add_test(tc1_1, s21_strtok_empty);
    tcase_add_test(tc1_1, s21_strerror_positive_0);
    tcase_add_test(tc1_1, s21_strerror_positive_106);
    tcase_add_test(tc1_1, s21_strerror_negative_minus1);
    tcase_add_test(tc1_1, s21_strerror_negative_107);
    tcase_add_test(tc1_1, s21_strerror_negative_minus1000);
    tcase_add_test(tc1_1, s21_strerror_negative_1000);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
